/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author paulh
 */
public class interface_plateau extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(interface_plateau.class.getName());

    boolean F=true;
    boolean M=false;
    boolean D=false;
    String score;
    /**
     * Creates new form interface_plateau
     */
    public interface_plateau() {
        initComponents(); 
        Bt_facile.setBorder(null);
        Bt_moyen.setBorder(null);
        Bt_difficile.setBorder(null);
        jPanel1.setLayout(new java.awt.GridLayout(5,5));
        metier jeu = new metier();
        for (int i=0; i < 5; i++){ for (int j=0;j < 5; j++){
            Cellule c = jeu.grille[i][j];
            JbuttonAmeliore b = new JbuttonAmeliore(i,j,c); 
            jPanel1.add(b);
            b.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt){
                jeu.deplacerCheval(b.cooX,b.cooY);
                repaint();
            if (jeu.estVictoire()) {
                Lb_resultat.setText("Victoire !");
            } 
            else if (jeu.estDefaite()) {
                Lb_resultat.setText("Défaite !");
    }}
                    });
        }
      }
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Bt_recommencer = new javax.swing.JButton();
        Lb_resultat = new javax.swing.JLabel();
        Bt_difficile = new javax.swing.JButton();
        Bt_moyen = new javax.swing.JButton();
        Bt_facile = new javax.swing.JButton();
        Bt_menu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        jCheckBox2.setText("jCheckBox2");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 490, 450));

        Bt_recommencer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Bt_recommencer.setText("RECOMMENCER");
        Bt_recommencer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        Bt_recommencer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bt_recommencerMouseClicked(evt);
            }
        });
        Bt_recommencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_recommencerActionPerformed(evt);
            }
        });
        getContentPane().add(Bt_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, 110, 20));

        Lb_resultat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Lb_resultat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lb_resultat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 255), 3));
        getContentPane().add(Lb_resultat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 100, 30));

        Bt_difficile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Bt_difficile.setForeground(new java.awt.Color(204, 0, 0));
        Bt_difficile.setText("DIFFICILE");
        Bt_difficile.setBorder(null);
        Bt_difficile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_difficileActionPerformed(evt);
            }
        });
        getContentPane().add(Bt_difficile, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, 80, 20));

        Bt_moyen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Bt_moyen.setForeground(new java.awt.Color(255, 204, 0));
        Bt_moyen.setText("MOYEN");
        Bt_moyen.setBorder(null);
        Bt_moyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_moyenActionPerformed(evt);
            }
        });
        getContentPane().add(Bt_moyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, 80, 20));

        Bt_facile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Bt_facile.setForeground(new java.awt.Color(51, 204, 0));
        Bt_facile.setText("FACILE");
        Bt_facile.setBorder(null);
        Bt_facile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_facileActionPerformed(evt);
            }
        });
        getContentPane().add(Bt_facile, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 80, 20));

        Bt_menu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Bt_menu.setText("MENU");
        Bt_menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        Bt_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_menuActionPerformed(evt);
            }
        });
        getContentPane().add(Bt_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 560, 110, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 600));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 153), 3));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 570, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_moyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_moyenActionPerformed
        // TODO add your handling code here:
        
        Bt_moyen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 3));
        Bt_difficile.setBorder(null);
        Bt_facile.setBorder(null);
    }//GEN-LAST:event_Bt_moyenActionPerformed

    private void Bt_facileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_facileActionPerformed
        // TODO add your handling code here:
        
        Bt_facile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0), 3));
        Bt_moyen.setBorder(null);
        Bt_difficile.setBorder(null);
    }//GEN-LAST:event_Bt_facileActionPerformed

    private void Bt_difficileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_difficileActionPerformed
        // TODO add your handling code here:
        
        Bt_difficile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 3));
        Bt_moyen.setBorder(null);
        Bt_facile.setBorder(null);
    }//GEN-LAST:event_Bt_difficileActionPerformed

    private void Bt_recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_recommencerActionPerformed
        // TODO add your handling code here:
        
        score="";
        Lb_resultat.setText(""+score);
        Bt_difficile.setBorder(null);
        Bt_moyen.setBorder(null);
        Bt_facile.setBorder(null);
    }//GEN-LAST:event_Bt_recommencerActionPerformed

    private void Bt_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_menuActionPerformed
        // TODO add your handling code here:
        Menu_Jeu f = new Menu_Jeu(); 
        f.setVisible(true) ; 
        this.dispose();
    }//GEN-LAST:event_Bt_menuActionPerformed

    private void Bt_recommencerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt_recommencerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Bt_recommencerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new interface_plateau().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_difficile;
    private javax.swing.JButton Bt_facile;
    private javax.swing.JButton Bt_menu;
    private javax.swing.JButton Bt_moyen;
    private javax.swing.JButton Bt_recommencer;
    private javax.swing.JLabel Lb_resultat;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
