/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author paulh
 */
public class Menu_Jeu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu_Jeu.class.getName());

    /**
     * Creates new form Menu_Jeu
     */
    public Menu_Jeu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bt_jouer = new javax.swing.JButton();
        Nom_Du_Jeu = new javax.swing.JLabel();
        Bt_quitter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bt_jouer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Bt_jouer.setText("JOUER");
        Bt_jouer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        Bt_jouer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_jouerActionPerformed(evt);
            }
        });
        getContentPane().add(Bt_jouer, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 80, 30));

        Nom_Du_Jeu.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        Nom_Du_Jeu.setForeground(new java.awt.Color(0, 204, 51));
        Nom_Du_Jeu.setText("LA");
        getContentPane().add(Nom_Du_Jeu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 60, 50));

        Bt_quitter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Bt_quitter.setText("QUITTER");
        Bt_quitter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        Bt_quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_quitterActionPerformed(evt);
            }
        });
        getContentPane().add(Bt_quitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 80, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("CHEVAUCH2E");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 320, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 204));
        jLabel2.setText("FANTASTIQUE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 204), 3));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 370));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 400));

        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0), 3));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 440, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_jouerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_jouerActionPerformed
        // TODO add your handling code here:
        interface_plateau f = new interface_plateau(); 
        f.setVisible(true) ; 
        this.dispose();
    }//GEN-LAST:event_Bt_jouerActionPerformed

    private void Bt_quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_quitterActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Bt_quitterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu_Jeu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_jouer;
    private javax.swing.JButton Bt_quitter;
    private javax.swing.JLabel Nom_Du_Jeu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
